/*
 * This source file was generated by the Gradle 'init' task
 */
package pl.waw.oledzki.signpost

import org.scalatest.wordspec.AnyWordSpec
import org.scalatest.matchers.should.Matchers

class AppTest extends AnyWordSpec with Matchers {
  "App" should {
    "have a greeting" in {
      "a" shouldBe("a")
    }
  }
}
